# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "jekyll", "~> 4.3"

# gem "github-pages", "~> 231", group: :jekyll_plugins

gem "minimal-mistakes-jekyll", "~> 4.24"

group :jekyll_plugins do
  gem "jekyll-compose", "~> 0.12.0"
  gem "jekyll-include-cache", "~> 0.2.1"
  gem "jekyll-feed", "~> 0.17.0"
  gem "jekyll-seo-tag", "~> 2.8"
  gem "jekyll-paginate", "~> 1.1"
  gem "jekyll-sitemap", "~> 1.4"
  gem "jekyll-gist", "~> 1.5"
end

gem "faraday-retry", "~> 2.2"

gem "tzinfo-data", "~> 1.2024"
